asm_translationloader_admin_show:
    path:  /admin/translations.html
    defaults: { _controller: AsmTranslationLoaderBundle:TranslationAdmin:show }

asm_translationloader_admin_show_filter:
    path:  /admin/translations/show/{locale}/{domain}
    defaults: { _controller: AsmTranslationLoaderBundle:TranslationAdmin:show }

asm_translationloader_admin_create:
    path:  /admin/translations/create
    defaults: { _controller: AsmTranslationLoaderBundle:TranslationAdmin:create }

asm_translationloader_admin_edit:
    path:  /admin/translations/edit
    defaults: { _controller: AsmTranslationLoaderBundle:TranslationAdmin:edit }

asm_translationloader_admin_delete:
    path:  /admin/translations/delete
    defaults: { _controller: AsmTranslationLoaderBundle:TranslationAdmin:delete }
