parameters:
#    asm_translation.example.class: Asm\TranslationLoaderBundle\Example

services:
#    asm_translation.example:
#        class: %asm_translation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
