parameters:

services:
    translation.loader.db:
        class:     Asm\TranslationLoaderBundle\Translation\DatabaseLoader
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: translation.loader, alias: db}
