parameters:

services:
    translation.loader.db:
        class:     Asm\TranslationLoaderBundle\Translation\DatabaseLoader
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: translation.loader, alias: db}

    asm_translation_loader.history.subscriber:
        class: Asm\TranslationLoaderBundle\EventListener\TranslationHistorySubscriber
        calls:
            - [ setEnabled, [ "%asm_translation_loader.history.enabled%" ] ]
        tags:
            - { name: doctrine.event_subscriber }
