parameters:
    translation_loader.database.entity_manager: default
    translation_loader.history.enabled:         false

services:
    translation.loader.db:
        class:     Asm\TranslationLoaderBundle\Translation\DatabaseLoader
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: translation.loader, alias: db}

    asm_translation_loader.subscriber:
        class: Asm\TranslationLoaderBundle\EventListener\TranslationHistorySubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: "%translation_loader.database.entity_manager%" }
